# Generated by Django 2.0.5 on 2019-09-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190917_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='codcliente',
            new_name='codcliente_id',
        ),
    ]
