# Generated by Django 2.0.5 on 2019-09-18 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20190917_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codcliente_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='codcliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Cliente'),
        ),
    ]
