# Generated by Django 2.0.5 on 2019-09-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20190918_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='idproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='idclientes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='codfacturac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='codproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallecreditos',
            name='codproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledia',
            name='iddia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallegasto',
            name='idgasto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleingreso',
            name='idingreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='codnotacredito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='codproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='codfacturav',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='codproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_municipio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtncredito',
            name='codncredito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtncredito',
            name='codproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='codproveedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='codcliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='idcategasto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='cod_departamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncredito',
            name='codfacturac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncredito',
            name='codproveedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='codfacturac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='codproveedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='idfacturav',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablaprecios',
            name='codcliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablaprecios',
            name='codproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
