# Generated by Django 2.0.5 on 2019-09-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20190918_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bodega',
        ),
    ]
