# Generated by Django 2.0.5 on 2019-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_delete_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.AlterField(
            model_name='productos',
            name='codproducto',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
