from django.contrib import admin
from .models import *


# Register your models here.
admin.site.register(Categoria)
admin.site.register(Productos)
admin.site.register(Cajas)
admin.site.register(Categasto)
admin.site.register(Cateingreso)
admin.site.register(Cliente)
admin.site.register(Clientes)
admin.site.register(Configuraciones)
admin.site.register(Proveedor)
admin.site.register(Facturacompra)
admin.site.register(Facturaventa)
admin.site.register(Creditos)
admin.site.register(Departamentos)
admin.site.register(Detallecompra)
admin.site.register(Detallecreditos)
admin.site.register(Dia)
admin.site.register(Detalledia)
admin.site.register(Gastos)
admin.site.register(Detallegasto)
admin.site.register(Ingresos)
admin.site.register(Detalleingreso)
admin.site.register(Ncredito)
admin.site.register(Notacredito)
admin.site.register(Detallenotacredito)
admin.site.register(Detalleventa)
admin.site.register(Municipios)
admin.site.register(Direccion)
admin.site.register(Dtncredito)
admin.site.register(Fechaabono)
admin.site.register(Grp)
admin.site.register(Grpusr)
admin.site.register(Menu)
admin.site.register(Movimiento)
admin.site.register(Notificaciones)
admin.site.register(Numeros)
admin.site.register(Permisos)
admin.site.register(Respaldos)
admin.site.register(Tablaprecios)
admin.site.register(Tirajes)
admin.site.register(Turno)
admin.site.register(Usr)
